module.exports = {
    CONNECT: "connect",
    USER_TYPE_ADMIN: "admin",
    USER_TYPE_STUDENT: "student",
    USER_TYPE_TEACHER: "teacher",
    USER_TYPE_PARENT: "parent",
    MONGO_DB_NAME : "school_database",
    ADMIN_COLLECTION_NAME: "admins",
    CHAT_MESSAGES_COLLECTION_NAME: "chat_messages",
    CHAT_ONLINE_USERS_COLLECTION_NAME : "chat_online_users",
    STUDENT_COLLECTION_NAME: "students",
    TEACHER_COLLECTION_NAME: "teachers",
    PARENT_COLLECTION_NAME: "parents",
    ATTENDANCE_COLLECTION_NAME: "attendances",
    FEE_COLLECTION_NAME: "fees",
    AUTH_COLLECTION_NAME: "auths",
    ACCESS_LEVEL_COLLECTION_NAME: "access_levels",
    ED_QUALIFICATION_COLLECTION_NAME: "ed_qualification",
    ED_SPECIALITY_COLLECTION_NAME: "ed_speciality",
    EXTRA_ACTIVITY_POSITION_COLLECTION_NAME: "extra_activity_position",
    TOKEN_COLLECTION_NAME: "tokens",
    MEETING_COLLECTION_NAME: "meetings",
    HOMEWORK_DIRECTORY_PATH: "./uploads/homework/"
};