module.exports = {
  CONNECT: "connect",
  USER_TYPE_ADMIN: "admin",
  USER_TYPE_STUDENT: "student",
  USER_TYPE_TEACHER: "teacher",
  USER_TYPE_PARENT: "parent",
  MONGO_DB_NAME: "school_database",
  CHAT_MESSAGES_COLLECTION_NAME: "chat_messages",
  CHAT_ONLINE_USERS_COLLECTION_NAME: "chat_online_users",
  ATTENDANCE_COLLECTION_NAME: "attendances",
  FEE_COLLECTION_NAME: "fees",
  AUTH_COLLECTION_NAME: "auths",
  TOKEN_COLLECTION_NAME: "tokens",
  HOMEWORK_COLLECTION_NAME: "homeworks",
  MEETING_COLLECTION_NAME: "meetings",
  HOMEWORK_DIRECTORY_PATH: "./uploads/homework/",

  // DF tables
  DF_ACCESS_LEVEL_COLLECTION_NAME: "df_access_levels",
  DF_ED_QUALIFICATION_COLLECTION_NAME: "df_ed_qualifications",
  DF_ED_SPECIALITY_COLLECTION_NAME: "df_ed_specialities",
  DF_EXTRA_ACTIVITY_POSITION_COLLECTION_NAME: "df_extra_activity_positions",
  DF_EXTRA_ACTIVITY_TYPE_COLLECTION_NAME: "df_extra_activity_types",
  DF_GRADE_COLLECTION_NAME: "df_grades",
  DF_INSTITUTE_COLLECTION_NAME: "df_institutes",
  DF_MARITAL_STATUS_COLLECTION_NAME: "df_marital_statuses",
  DF_OCCUPATION_COLLECTION_NAME: "df_occupations",
  DF_OCCUPATION_CATEGORY_COLLECTION_NAME: "df_occupation_categories",
  DF_RELATION_TYPE_COLLECTION_NAME: "df_relation_types",
  DF_SUBJECT_COLLECTION_NAME: "df_subjects",
  DF_TEACHER_GRADE_COLLECTION_NAME: "df_teacher_grades",
  DF_TITLE_COLLECTION_NAME: "df_titles",
  DF_USER_TYPE_COLLECTION_NAME: "df_user_types",

  // M tables
  M_ADMIN_COLLECTION_NAME: "m_admins",
  M_STUDENT_COLLECTION_NAME: "m_students",
  M_TEACHER_COLLECTION_NAME: "m_teachers",
  M_PARENT_COLLECTION_NAME: "m_parents",
  M_CLASS_COLLECTION_NAME: "m_classes",
  M_CLASS_SECTION_COLLECTION_NAME: "m_class_sections",
  M_SUBJECT_COLLECTION_NAME: "m_subjects",
  M_EXTRA_ACTIVITY_COLLECTION_NAME: "m_extra_activities",
  M_MARKS_COLLECTION_NAME: "m_marks",
  M_ORGANIZATION_COLLECTION_NAME: "m_organizations",

  // REL tables
  REL_EXTRA_ACTIVITY_TEACHER_COLLECTION_NAME: "rel_extra_activity_teacher",
  REL_PARENT_STUDENT_COLLECTION_NAME: "rel_parent_student",
  REL_STUDENT_ACTIVITY_COLLECTION_NAME: "rel_student_activity",
  REL_STUDENT_ACTIVITY_POSITION_COLLECTION_NAME:
    "rel_student_activity_position",
  REL_STUDENT_CLASS_COLLECTION_NAME: "rel_student_class",
  REL_TEACHER_CLASS_COLLECTION_NAME: "rel_teacher_class",
  REL_TEACHER_QUALIFICATION_COLLECTION_NAME: "rel_teacher_qualification",
  REL_TEACHER_SUBJECT_CLASS_COLLECTION_NAME: "rel_teacher_subject_class",
};
