module.exports = {
    CONNECT: "connect",
    USER_TYPE_ADMIN: "admin",
    USER_TYPE_STUDENT: "student",
    USER_TYPE_TEACHER: "teacher",
    USER_TYPE_PARENT: "parent",
    MONGO_DB_NAME : "school_database",
    ADMIN_COLLECTION_NAME: "admins",
    CHAT_MESSAGES_COLLECTION_NAME: "chat_messages",
    CHAT_ONLINE_USERS_COLLECTION_NAME : "chat_online_users",
    STUDENT_COLLECTION_NAME: "students",
    TEACHER_COLLECTION_NAME: "teachers",
    PARENT_COLLECTION_NAME: "parents",
    ATTENDANCE_COLLECTION_NAME: "attendances",
    FEE_COLLECTION_NAME: "fees",
    AUTH_COLLECTION_NAME: "auths",
    TOKEN_COLLECTION_NAME: "tokens",
    MEETING_COLLECTION_NAME: "meetings",
    HOMEWORK_DIRECTORY_PATH: "./uploads/homework/",

    // DF tables
    DF_ACCESS_LEVEL_COLLECTION_NAME: "df_access_levels",
    DF_ED_QUALIFICATION_COLLECTION_NAME: "df_ed_qualification",
    DF_ED_SPECIALITY_COLLECTION_NAME: "df_ed_speciality",
    DF_EXTRA_ACTIVITY_POSITION_COLLECTION_NAME: "df_extra_activity_position",
    DF_EXTRA_ACTIVITY_TYPE_COLLECTION_NAME: "df_extra_activity_type",
    DF_GRADE_COLLECTION_NAME: "df_grades",
    DF_INSTITUTE_COLLECTION_NAME: "df_institutes",
    DF_MARITAL_STATUS_COLLECTION_NAME: "df_marital_status",
    DF_OCCUPATION_COLLECTION_NAME: "df_occupation",
    DF_OCCUPATION_CATEGORY_COLLECTION_NAME: "df_occupation_category",
    DF_RELATION_TYPE_COLLECTION_NAME: "df_relation_type",
    DF_SUBJECT_COLLECTION_NAME: "df_subject",
    DF_TEACHER_GRADE_COLLECTION_NAME: "df_teacher_grade",
    DF_TITLE_COLLECTION_NAME: "df_title",
    DF_USER_TYPE_COLLECTION_NAME: "df_user_type",
};